### ISSUE TITLE
option to read jsonl instead of json files

### ISSUE THREAD

**Issue by zmallen** [center-for-threat-informed-defense/sightings_ecosystem#5]
When loading sightings data under `./data`, https://github.com/center-for-threat-informed-defense/sightings_ecosystem/blob/main/src/pipeline/pipeline.py#L218 assumes that a file will be one massive JSON blob. 

This can become untenable for large JSON blobs of sightings data, as python can be [inefficient](https://pythonspeed.com/articles/json-memory-streaming/) at processing larger files. This is especially true for high throughput applications that can log millions to tens-of-millions of logs to sightings per day.

I recommend the ability to load files as `jsonl`, which are newline delimited json blobs for sightings.  You can then setup sidecards/forwarders (i am using https://vector.dev) to append to a file within the sightings ecosystem

**Comment by mehaase** [comment]
Great idea, thank you! I will include this in the planning for our next iteration.
